{% set name = "gevent" %}
{% set version = "24.10.2" %}
{% set sha256 = "96e7bab9de56e0aca3858b8bc9c71f4eb0c0e12b7cf3cbfd170b62ce68cf71d7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:   # [unix]
    - 0001-Allow-include-flags-to-be-present-in-CFLAGS.patch        # [unix]
    - 0002-Allow-library-flags-to-be-present-in-LDFLAGS.patch       # [unix]
    - 0003-Allow-macro-to-be-present-in-CFLAGS.patch                # [unix]
    - 0004-Drop-isysroot-if-CONDA_BUILD_SYSROOT-is-specified.patch  # [unix]

build:
  number: 0
  script:
    - export GEVENTSETUP_EMBED_LIBEV=0 GEVENTSETUP_EMBED_LIBUV=0 GEVENTSETUP_EMBED_CARES=0  # [unix]
    - copy %SRC_DIR%\deps\c-ares\ares_build.h.dist %SRC_DIR%\deps\c-ares\ares_build.h       # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi >=1.17.1                          # [build_platform != target_platform]
    - cython >=3.0.11                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - libmagic  # [unix]
    - make      # [unix]

  host:
    - cffi >=1.17.1
    - cython >=3.0.11
    - pip
    - setuptools >=40.8.0
    - greenlet >=3.0.3
    - python
    - libev     # [unix]
    - libuv     # [unix]
    - c-ares    # [unix]

  run:
    - cffi >=1.17.1
    - python
    - greenlet >=3.1.1
    - zope.event
    - zope.interface
    - setuptools

test:
  requires:
    - pip
  imports:
    - gevent
    - gevent.libev
    - gevent.libuv
    - gevent.resolver
  commands:
    - python -m pip check

about:
  home: https://www.gevent.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Coroutine-based network library
  description: |
    Gevent uses greenlet to provide a high-level synchronous API on top of the libev event loop.
  doc_url: https://www.gevent.org/contents.html
  dev_url: https://github.com/gevent/gevent

extra:
  recipe-maintainers:
    - beenje
    - nehaljwani
